import 'package:flutter_test/flutter_test.dart';
import 'package:rr_movie_workshop/core/constants/genres.dart';

/// Pins `layoutVisibleRect` to the exact values produced by Python's
/// `get_layout_visible_rect` (RR_VHS_Tool.py:634-665).  The numbers below
/// were generated by running the Python implementation directly and
/// printing each rect; if either side drifts the diff will be obvious.
void main() {
  group('layoutVisibleRect parity with Python', () {
    test('layout 1 — wide', () {
      final r = layoutVisibleRect(1)!;
      expect(r.top, closeTo(30.0, 1e-9));
      expect(r.bottom, closeTo(1622.0, 1e-6));
      expect(r.left, closeTo(31.0, 1e-9));
      expect(r.right, closeTo(1024.0, 1e-9));
    });
    test('layout 2', () {
      final r = layoutVisibleRect(2)!;
      expect(r.top, closeTo(30.0, 1e-9));
      expect(r.bottom, closeTo(1630.0, 1e-9));
      expect(r.left, closeTo(23.97107114933553, 1e-9));
      expect(r.right, closeTo(1021.0, 1e-9));
    });
    test('layout 3', () {
      final r = layoutVisibleRect(3)!;
      expect(r.top, closeTo(31.0, 1e-9));
      expect(r.bottom, closeTo(1631.0, 1e-9));
      expect(r.left, closeTo(23.97107114933553, 1e-9));
      expect(r.right, closeTo(1021.0, 1e-9));
    });
    test('layout 4 — left-aligned at x=0', () {
      final r = layoutVisibleRect(4)!;
      expect(r.top, closeTo(0.0, 1e-9));
      expect(r.bottom, closeTo(1623.0, 1e-9));
      expect(r.left, closeTo(4.238938053097527, 1e-9));
      expect(r.right, closeTo(1024.0, 1e-9));
    });
    test('layout 5 — wide', () {
      final r = layoutVisibleRect(5)!;
      expect(r.top, closeTo(30.0, 1e-9));
      expect(r.bottom, closeTo(1622.0, 1e-6));
      expect(r.left, closeTo(31.0, 1e-9));
      expect(r.right, closeTo(1024.0, 1e-9));
    });
    test('returns null for invalid layouts', () {
      expect(layoutVisibleRect(0), isNull);
      expect(layoutVisibleRect(-1), isNull);
      expect(layoutVisibleRect(6), isNull);
      expect(layoutVisibleRect(99), isNull);
    });
  });
}
