name: rr_movie_workshop
description: "RR Movie Workshop - Retro Rewind modding tool (Flutter desktop port)"
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  path: ^1.9.0
  image: ^4.1.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
